repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: []
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.335
    hooks:
    - id: pyright