[tool.poetry]
name = "zebra-puzzles"
version = "0.1.0"
description = "Create and solve zebra / Einstein puzzles"
authors = ["Tushar Chandra"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pycosat = "^0.6.3"
mypy = "^0.701.0"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
toml = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
